import exampleManifest  from "./example.json" with { type: 'json' };
const generateManifest = document.querySelector("#generateManifestBtn");
const displayName = document.querySelector("#displayName");
const contactEmail = document.querySelector("#contactEmail");
const vendor = document.querySelector("#vendor");
const description = document.querySelector("#description");

displayName.value = exampleManifest.displayName;
contactEmail.value = exampleManifest.email;
vendor.value = exampleManifest.vendor;
description.value = exampleManifest.description;


generateManifest.addEventListener("click", () => { 
    console.log("Generate Manifest");
    console.log(exampleManifest);

    const manifest = {
        ...exampleManifest,
        id: crypto.randomUUID(), 
        displayName: "Workspace Metrics Exporter",
        vendor: "Workspace Metrics Exporter",
        email: "workspace@metrics.exporter",
        description: "Auto generated by Workspace Metrics Exporter manifest",
        descriptionUrl: "",
        availability: "org_private",
    };

    console.log(manifest);

    downloadManifest(manifest);

});


/**
 * Triggers a browser download of JSON data as 'manifest.json'
 * @param {Object|string} data - The JSON object or JSON string to download
 */
function downloadManifest(data) {
    // 1. Safely convert to a pretty-printed JSON string if it's a standard JS object
    const jsonString = typeof data === 'object' 
      ? JSON.stringify(data, null, 2) 
      : data;
  
    // 2. Create a Blob object representing the data as a valid JSON file
    const blob = new Blob([jsonString], { type: 'application/json' });
  
    // 3. Generate a temporary, internal browser URL for that Blob
    const url = URL.createObjectURL(blob);
  
    // 4. Create a hidden anchor element
    const link = document.createElement('a');
    link.href = url;
    link.download = 'manifest.json';
  
    // 5. Attach to the DOM, trigger the click, and immediately destroy it
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  
    // 6. Free up the memory used by the Blob URL
    URL.revokeObjectURL(url);
  }
